Ws 18 internationalization
salalo/flat-search pull request #19
Opened 2021-07-28 14:08 UTC by salalo

#18

2021-07-28 14:40 UTC, salalo commented
This branch was created on top of #17  - this is the cause of first commit duplicate

2021-07-29 08:16 UTC, boksadawid requested changes

2021-07-29 08:16 UTC, boksadawid commented on lib/flat_search_web/live/page_live.ex
> +       locale: locale
`locale: Map.get(session, "locale", "pl")`

2021-07-29 08:16 UTC, boksadawid commented on lib/flat_search_web/plug/local_plug.ex
> +        |> put_session(:locale, locale)
`put_session(conn, :locale, locale)` - pipe isn't needed here since it's one function

2021-07-29 08:16 UTC, boksadawid commented on lib/flat_search_web/plug/local_plug.ex
> +        (known_locales -- accepted_languages)
`Enum.filter(know_locales, fn locale -> locale in accepted_languages)`?

2021-07-29 08:16 UTC, boksadawid commented on lib/flat_search_web/plug/local_plug.ex
> +        (known_locales -- accepted_languages)
also you can change accepted_languages to accepted_locales, to be consistent with one naming

2021-07-29 08:16 UTC, boksadawid commented on lib/flat_search_web/plug/local_plug.ex
> +  # https://raw.githubusercontent.com/smeevil/set_locale/fd35624e25d79d61e70742e42ade955e5ff857b8/lib/headers.ex
👍🏻 for honesty

2021-07-29 08:54 UTC, boksadawid approved these changes

2021-07-29 09:00 UTC, merged